spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

    # url: jdbc:mysql://localhost:3306/dodal
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # username: root
    # password: root

  flyway:
    enabled: false
  #   baseline-on-migrate: true
  #   locations: classpath:db/migration
  #   table: dodal_flyway_schema_version
