spring:
  datasource:
    url: ENC(1FSuCtiVuHL0xlOwhkbdJAHHqTNnoI9uV077uicXwzKiz7IYcqsRD02sGeSN/u/SZKdlZbtPdQaGQqqzjxv0e2oCNisKXZtUtth1L/0YnXF5A9nxg+z8/K1Z6/dt0YsMbVcgeksO5dPynlRruuQ5B8JswdL+0cQT210TWjqG0rq/+AC2+E9I7g==)
    username: ENC(d2Uv0aL3W6lvd5x/fOfM5/LVwbZq2D8W)
    password: ENC(xCKtMm5BtfDbGJh2w0X/dbSQvkpHR7na)

jwt:
  secret: ENC(hp14qv/4tmW3/d1xoygJlrjX2Hj658Ruqm+fjTwG4xBkrDzpN7u7STBvtaPvWIxMck/f06AT5ySZ0Jo9xu75pq1YFByHlK9QJZryT7qzHrqA6VYKdkY7Y+YdwVlG3sZfiCfbP2z3Y8NGqjSRRWcaxyWksnPlT/uXJ6eyRDkB5KFvFynvqhHU0q3Z/B8JRTts)
  access-token-validity-in-milli-seconds: ENC(QukQXX9xhFAnuUF0IiwoPg==)
  refresh-token-validity-in-milli-seconds: ENC(8U0nryOJ+bP1FSXBO1Rr9qdwIia5pjSo)