spring:
  application:
    name: dodal

  profiles:
    active: local

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Jasypt
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
