spring:
  application:
    name: dodal

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: dodal_flyway_schema_version

  security:
    oauth2:
      apple:
        grant_type: ENC(UA5rYw9fjUYIDFSEgzGVFdU122CQXItZ0yZpk6r3MzQ=)
        redirect-uri: ENC(2BAMs0/HnVB69/oVKLeYDm+5nzyv2q55Y+toPOAS6/JAZ7DzKxP+mMuE+jHwIreyQBC4aZ7HE9Pfd5yw8f+C1w==)
        key-id: ENC(Xn4wau7bP3RblVIeAnUSr1ALmWFN843F)
        public-key-uri: https://appleid.apple.com/auth/oauth2/v2/keys
        client:
          client-id: ENC(tjgLIg7i4IA7BeOO0UfC3cVWzuMwIhBk65uHlrq9ZgI=)
          team-id: ENC(XsmL8nWsaZX89Ndx0a9qLuQb128Dcuxg)
          client-secret: ENC(GWqF1EhbQFwDyzJogwhUDl7EaxOCFpl43xJZQ6hDA7seB6VK54G1qFY9Cpn12my5VF4nIrhz2y7l5z9DlnfsxX8VhUzjc5jQVpq2ehrEK1CqDR0dvRlUWXjlkpe1XYpiC55sqPPp5a2ge5FcKcJYlQAVFzEnRRCK2GOlAZUtgQyxayioZiA02TmwwIo9uHI9EJWDig3Ec8ghElS6u2KFIfitNx0fJuhUMk3MQ0BYbDeX0HztJX3eFE7I3gqskEYkp4Iv+uJG+uQZXqzifAuuulNn0BKyahhcChdqiefHWmJU3dvQ4zlWHq7uGCNN05TysoQpdXYRbUe2arMuLD0lgEWOEHm9S0/E57ibZ1H8Ofg=)

# Jasypt
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

jwt:
  secret: ENC(hp14qv/4tmW3/d1xoygJlrjX2Hj658Ruqm+fjTwG4xBkrDzpN7u7STBvtaPvWIxMck/f06AT5ySZ0Jo9xu75pq1YFByHlK9QJZryT7qzHrqA6VYKdkY7Y+YdwVlG3sZfiCfbP2z3Y8NGqjSRRWcaxyWksnPlT/uXJ6eyRDkB5KFvFynvqhHU0q3Z/B8JRTts)
  access-token-validity-in-milli-seconds: ENC(QukQXX9xhFAnuUF0IiwoPg==)
  refresh-token-validity-in-milli-seconds: ENC(8U0nryOJ+bP1FSXBO1Rr9qdwIia5pjSo)

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
        exclude: env, configprops, beans, mappings, heapdump, threaddump, loggers, caches, scheduledtasks, flyway