spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(1FSuCtiVuHL0xlOwhkbdJAHHqTNnoI9uV077uicXwzKiz7IYcqsRD02sGeSN/u/SZKdlZbtPdQaGQqqzjxv0e2oCNisKXZtUtth1L/0YnXF5A9nxg+z8/K1Z6/dt0YsMbVcgeksO5dPynlRruuQ5B8JswdL+0cQT210TWjqG0rq/+AC2+E9I7g==)
    username: ENC(d2Uv0aL3W6lvd5x/fOfM5/LVwbZq2D8W)
    password: ENC(xCKtMm5BtfDbGJh2w0X/dbSQvkpHR7na)
