spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dodal
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: dodal_flyway_schema_version
